
server:
  port: 8000
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  config:
    import: optional:file:.env[.properties]
            classpath:../../../.env
jwt: ${JWT}
mailjet:
  apikey: ${MAILJET_API_KEY}
  secretKey: ${MAILJET_SECRET_KEY}

